# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 00:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=10)),
                ('duration', models.IntegerField(default=0)),
                ('batch', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
