# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('enrol', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrolments',
            new_name='Enrolment',
        ),
    ]
